services:
  - type: web
    name: freefire-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: BOT_TOKEN
        sync: false # Keep this secret
      - key: ADMIN_ID
        sync: false # Keep this secret
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: freefire-bot
          property: url